[package]
name = "rust_raytracing"
version = "0.1.0"
authors = ["Mimoja <git@mimoja.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glm = "*"
sdl2 = "*"
rand = "*"
instant = "*"
rayon = "*"
image = "*"